function init(self)
	msg.post("#camera", "acquire_camera_focus")
	self.display_width = sys.get_config_number("display.width")
	self.display_height = sys.get_config_number("display.height")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("follow") then
		go.set_parent(".", sender)

		go.set_position(vmath.vector3(-self.display_width / 2, -self.display_height / 2, 0))
	elseif message_id == hash("unfollow") then
		go.set_parent("camera", nil, true)
	end
end